services:
  - type: web
    name: weatherme-push-server
    runtime: python
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.9
